version: "2"
services:
  backend:
    container_name: backend
    build:
      context: .
    environment:
      - ENV_Setting=local
    command: [
        "bash",
        "-c",
        "yes | python manage.py makemigrations --merge
        && yes | python manage.py makemigrations && yes | python manage.py migrate && python manage.py runserver 0.0.0.0:8000",
      ]
    volumes:
      - .:/code
    ports:
      - "8000:8000"